apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-014617-eyyp-service
spec:
  selector:
    app: enterprise-system-014617-eyyp
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
